### ISSUE TITLE
Crash on simultaneous marker move and marker delete

### ISSUE THREAD

**Issue by Axle1975** [Axle1975/TADR#4]
Place a marker.
Then while dragging it around with left mouse button, simultaneously erase it with right mouse button.
As soon as right mouse button is release, or very soon after, TA will crash.

**Comment by KevinHake** [comment]
A bunch of questions:
1. What's the background on the crash? Null pointer dereference? Delete on invalid memory location? 
2. What is it about moving and deleting at the same time that causes this to happen? 
3. Is this all happening in a single thread?
4. Possibly unrelated to this particular bug, but related to the code involved - does the local player modify these marker structures in a separate thread from the messages coming in on the network from peers? If that's the case I wonder if contention over the same data is invalidating iterators or something.

These are things I'm looking into, but I appreciate it if you can answer any quickly and/or steer me in the right direction.

**Comment by Axle1975** [comment]
The crash that I'm able to replicate easily happens in skirmish single player mode.  User is simultaneously moving a marker and erasing the whiteboard.

In that context, the crash is due to a dangling pointer. Specifically the CurrentElement member of AlliesWhiteboard.  The element is erased from the map array and CurrentElement is left dangling.  Then the mouse move event is processed and a new GraphicText is constructed using the invalid CurrentElement pointer as a prototype.  Upon trying to find the strlen of the GraphicText's text, we get a crash due to garbage string data.

In the context of skirmish, this is all happening in one thread.

In the context of multiplayer, AlliesWhiteboard::ReceiveMarkers (processes incoming marker updates from peer) and AlliesWhiteboard::Message (processes user mouse/keyboard input) do in fact come from different threads and I don't see any mutex protection anywhere, and logs do indicate (rare) occasions where the two functions are running concurrently:

21204: Unlock
21204: [AlliesWhiteboard::ReceiveMarkers] ...
6404: [AlliesWhiteboard::Message] ...
21204: [AlliesWhiteboard::ReceiveMarkers] DONE 
6404: [AlliesWhiteboard::Message] DONE
6404: MapControl Message
6404: [AlliesWhiteboard::Message] ...
6404: [AlliesWhiteboard::Message] DONE
6404: MapControl Message

So yeah it looks like concurrency could be an issue too
